# please config the path of the checkpoints(log/cp_dir) 
# and the running logs(hydra/run/dir) before running the code


defaults:
  - _self_
  - data: SEEDV
  - model: cnn_att

seed: 7

log:
  run: 0
  proj_name: 'CLISA_FACED_new'
  exp_name: ''
  cp_dir: './daest_cp/'   



train:
  gpus: [2]
  valid_method: 10
  iftest: False
  n_subs: ${data.n_subs}
  lr: 0.0007
  wd: 0.00015
  loss_temp: 0.07
  max_epochs: 30
  min_epochs: 10
  patience: 30
  num_workers: 8
  restart_times: ${train.max_epochs}  # scheduler


mlp:
  # fea_dim: 256 #${model.n_timeFilters*model.n_msFilters*4}
  hidden_dim: [128,64]
  out_dim: ${data.n_class}
  dropout: 0.1
  bn: 'no'
  lr: 0.0005  #0.0005
  wd: 0.0022   #0.001-0.005
  max_epochs: 100
  min_epochs: 30
  patience: 30
  gpus: ${train.gpus}
  num_workers: ${train.num_workers}
  batch_size: 256

ext_fea:
  normTrain: True
  batch_size: 256
  mode: 'me'
  rn_decay: 0.990
  use_pretrain: True


hydra:
  job:
    chdir: true
  run:
    dir: ./daest_run/${data.dataset_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}_run${log.run}